### ISSUE TITLE
[Probably a deliberate design]The comment preview is white in dark mode

### ISSUE THREAD

**Issue by MFn233** [TurboWarp/scratch-gui#933]
The comment preview is white in light mode:
![image](https://github.com/TurboWarp/desktop/assets/103323756/c4116121-5c56-4cba-98e8-0b0e5ac2a1e1)

However, **in dark mode, it's also white**:
![image](https://github.com/TurboWarp/desktop/assets/103323756/0edb59ba-d5b6-46e3-a282-2b7fb02f7234)

I don't know if this was deliberately designed...
If so, please let me know
Otherwise, fix it please.

I made a user style to fix this.
```css
/*--color-scheme: dark; is dark mode, but idk how to detect it.*/
.sa-comment-preview-inner {
    color: rgb(255, 255, 255);
    background-color: rgb(0 0 0 / 90%);
    filter: drop-shadow(0px 5px 5px rgb(255 255 255 / 20%));
}
@supports (backdrop-filter: blur(16px)) {
    .sa-comment-preview-inner {
        background-color: rgb(0 0 0 / 75%);
        backdrop-filter: blur(16px);
    }
}
```

...and it worked well on turbowarp.org/editor
![image](https://github.com/TurboWarp/desktop/assets/103323756/a043fcde-1c2d-4457-99e4-712334e8c302)

I wanted to send a pull request, but i have no idea where to put the code...(and also i don't exactly know how to send a pull request)
and I am somehow weak in english, perhaps there may be content that you can't understand well, but I don't think there will be too much reading barriers
